### ISSUE TITLE
since update on 17/20/2020

### ISSUE THREAD

**Issue by XelZero** [michengs/guide-core#1]
since update today - i keep crashing over and over in VS (Conquest) - almost every time i get the following crash log - before the update - no crashes

[00:22:51.811] [dungeon-guide] ERROR: Error: [dispatch] write: failed to generate S_SPAWN_DROPITEM<8>:
Error: version 8 of message (name: "S_SPAWN_DROPITEM", code: 41375) is outdated and cannot be used anymore
    at Dispatch.write (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\node_modules\tera-network-proxy\lib\connection\dispatch.js:316:23)
    at NetworkModInterface.send (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\bin\mod.js:343:38)
    at Object.module.exports.spawn (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\events\handlers\spawn.js:112:19)
    at Handlers.<anonymous> (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:64:44)
    at Handlers.emit (events.js:223:5)
    at C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:112:17
    at Handlers.delay (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:131:4)
    at Handlers.trigger (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:106:15)
    at Object.__types.<computed> [as spawn] (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:73:19)
    at Item.render (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\spawn.js:317:18)
[00:22:51.821] [dungeon-guide] ERROR: Error: [dispatch] write: failed to generate S_SPAWN_DROPITEM<8>:
Error: version 8 of message (name: "S_SPAWN_DROPITEM", code: 41375) is outdated and cannot be used anymore
    at Dispatch.write (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\node_modules\tera-network-proxy\lib\connection\dispatch.js:316:23)
    at NetworkModInterface.send (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\bin\mod.js:343:38)
    at Object.module.exports.spawn (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\events\handlers\spawn.js:112:19)
    at Handlers.<anonymous> (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:64:44)
    at Handlers.emit (events.js:223:5)
    at C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:112:17
    at Handlers.delay (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:131:4)
    at Handlers.trigger (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:106:15)
    at Object.__types.<computed> [as spawn] (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:73:19)
    at Item.render (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\spawn.js:317:18)
[00:22:54.871] [dungeon-guide] ERROR: Error: [dispatch] write: failed to generate S_SPAWN_DROPITEM<8>:
Error: version 8 of message (name: "S_SPAWN_DROPITEM", code: 41375) is outdated and cannot be used anymore
    at Dispatch.write (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\node_modules\tera-network-proxy\lib\connection\dispatch.js:316:23)
    at NetworkModInterface.send (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\bin\mod.js:343:38)
    at Object.module.exports.spawn (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\events\handlers\spawn.js:112:19)
    at Handlers.<anonymous> (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:64:44)
    at Handlers.emit (events.js:223:5)
    at C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:112:17
    at Handlers.delay (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:131:4)
    at Handlers.trigger (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:106:15)
    at Object.__types.<computed> [as spawn] (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:73:19)
    at Item.render (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\spawn.js:317:18)
[00:22:54.882] [dungeon-guide] ERROR: Error: [dispatch] write: failed to generate S_SPAWN_DROPITEM<8>:
Error: version 8 of message (name: "S_SPAWN_DROPITEM", code: 41375) is outdated and cannot be used anymore
    at Dispatch.write (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\node_modules\tera-network-proxy\lib\connection\dispatch.js:316:23)
    at NetworkModInterface.send (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\bin\mod.js:343:38)
    at Object.module.exports.spawn (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\events\handlers\spawn.js:112:19)
    at Handlers.<anonymous> (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:64:44)
    at Handlers.emit (events.js:223:5)
    at C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:112:17
    at Handlers.delay (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:131:4)
    at Handlers.trigger (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:106:15)
    at Object.__types.<computed> [as spawn] (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:73:19)
    at Item.render (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\spawn.js:317:18)

i include the latter because it seems maybe its conflicting... which it didnt before today and they happen at the same time

[00:27:36.403] [dispatch] [fix-laggy-friends-list] handle: error running raw hook for C_UPDATE_FRIEND_INFO<raw>
hook: (anonymous) in fix-laggy-friends-list
data: 04001576
error: [dispatch] write: failed to generate S_UPDATE_FRIEND_INFO<1>:
Error: version 1 of message (name: "S_UPDATE_FRIEND_INFO", code: 23717) is deprecated and cannot be used for writing
    at Proxy.send (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\bin\mod.js:343:38)
    at Object.callback (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\fix-laggy-friends-list\index.js:17:29)
[00:27:36.501] [dispatch] [fix-laggy-friends-list] handle: error running raw hook for C_UPDATE_FRIEND_INFO<raw>
hook: (anonymous) in fix-laggy-friends-list
data: 04001576
error: [dispatch] write: failed to generate S_UPDATE_FRIEND_INFO<1>:
Error: version 1 of message (name: "S_UPDATE_FRIEND_INFO", code: 23717) is deprecated and cannot be used for writing
    at Proxy.send (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\bin\mod.js:343:38)
    at Object.callback (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\fix-laggy-friends-list\index.js:12:17)

**Comment by michengs** [comment]
now is ok
